### ISSUE TITLE
Not working after publication?

### ISSUE THREAD

**Issue by khamidjon** [YarikSOffice/lingver#27] opened 2020-04-21 13:25 UTC
Firstly, thank you for the library.

While I debug on my computer everything is working fine, when I publish to Play Store, and I download from there, then, if the default language of the device is English, the library is not working. If the default language is Russian, everything is working fine.

Could you help to solve the issue?

**Comment by YarikSOffice** [comment] 2020-04-22 13:35
Hi @khamidjon 

do you either use app bundles or strip resources via `resConfigs` in build.gradle?

Could you provide more details on how you use the library and what is the issue exactly?
A sample project representing the issue is highly appreciated as well.

**Comment by khamidjon** [comment] 2020-04-23 06:27
I have created string.xml, string-en.xml, string-ru.xml files I think this is what you mean by app bundles. I could not find resConfigs in build.gradle, I don't know what it is.

In my App.kt file, I am initializing based on user device's language, it is working fine.

`class App : Application() {

    @Suppress("UNUSED_VARIABLE")
    override fun onCreate() {
        super.onCreate()

        val language = Locale.getDefault().getLanguage()

        if(language.equals("ru") || language.equals("RU")){
            val store = PreferenceLocaleStore(this, Locale(LANGUAGE_RUSSIAN))
            val lingver = Lingver.init(this, store)
        }else{
            val store = PreferenceLocaleStore(this, Locale(LANGUAGE_ENGLISH))
            val lingver = Lingver.init(this, store)
        }


        // you can use this instance for DI or get it via Lingver.getInstance() later on

    }

    companion object {
        const val LANGUAGE_ENGLISH = "en"
        const val LANGUAGE_ENGLISH_COUNTRY = "US"
        const val LANGUAGE_UKRAINIAN = "uk"
        const val LANGUAGE_UKRAINIAN_COUNTRY = "UA"
        const val LANGUAGE_RUSSIAN = "ru"
        const val LANGUAGE_RUSSIAN_COUNTRY = "RU"
    }
}`

and through dialog, I am changing application language

`MaterialDialog(requireContext()).show {
                listItemsSingleChoice(R.array.languagechoose, initialSelection = initalIndex){ dialog, index, text ->
                    if(index != initalIndex){
                        if(index == 0){
                            setNewLocale(LANGUAGE_ENGLISH, LANGUAGE_ENGLISH_COUNTRY)
                        }else{
                            setNewLocale(LANGUAGE_RUSSIAN, LANGUAGE_RUSSIAN_COUNTRY)
                        }
                    }
                }
            }`

as I said, while I run on Android Studio, absolutely everything is working great. But after, I upload this version to Play Store and if the default language of the device is in Russian, changing language is working fine. 
But if default language is in English, if I want to change language to Russian, it keeps default English language.

**Comment by YarikSOffice** [comment] 2020-04-23 10:47
[App bundles](https://developer.android.com/guide/app-bundle) is a publishing format that optimises your apk for each device by removing unnecessary resources like strings, drawables, etc. According to your description, your app might be affected by that. You can find more info on app bundles in the [README](https://github.com/YarikSOffice/lingver/blob/master/README.md).

Apart from that, I don't see any issues in your code. Please consider submitting a sample project in case the issue won't be resolved by the suggestions above.

**Comment by khamidjon** [comment] 2020-05-06 13:15
Yes, it worked after I added following lines.

`android {
    bundle {
        language {
            // Specifies that the app bundle should not support
            // configuration APKs for language resources. These
            // resources are instead packaged with each base and
            // dynamic feature APK.
            enableSplit = false
        }
    }
}`

as you said, the problem was in the app bundle.
Thank you very much.

**Closed** 2020-05-06 13:18 UTC
